# Ollama Cloud
spring.ai.openai.api-key=${OLLAMA_API_KEY}
spring.ai.openai.chat.base-url=https://ollama.com
spring.ai.openai.chat.completions-path=/v1/chat/completions
#spring.ai.openai.chat.options.model=gpt-oss:120b
spring.ai.openai.chat.options.model=gemma3:27b