# Ollama Cloud
spring.ai.openai.api-key=80a036382761486e96929fd1744df818.VHx4nl4A0sdGH_z0CLopzwQ0
spring.ai.openai.chat.base-url=https://ollama.com
spring.ai.openai.chat.completions-path=/v1/chat/completions
#spring.ai.openai.chat.options.model=gpt-oss:120b
spring.ai.openai.chat.options.model=gemma3:27b